### ISSUE TITLE
Interest in NetCDF projection handling?

### ISSUE THREAD

**Issue by dblodgett-usgs** [hypertidy/ncmeta#14]
If you'd like the gridmapping and projection code from here: https://github.com/USGS-R/ncdfgeom/tree/master/R, I'd be more than happy to move it to `ncmeta` and update to match the data constructs used here. It is by no means perfect, but I've gotten a lot of mileage out of it and it is a good starting point for general parsing and conversion of the CF [`grid_mapping`](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch05s06.html) construct.

**Comment by mdsumner** [comment]
Sounds great! I looked at the geometry storage a while back, but a deeper look at ncdfgeom is on my list for early 2019.
