### ISSUE TITLE
libnetcdf.so.13: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bbo2adwuff** [hypertidy/ncmeta#30]
On linux I get following error when trying to install ncmeta:

```
* installing *source* package ‘ncmeta’ ...
** package ‘ncmeta’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/user/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/libs/RNetCDF.so':
  libnetcdf.so.13: cannot open shared object file: No such file or directory
```

There doesn't seem to be a `libnetcdf.so.13`, but I find `/usr/lib/libnetcdf.so` and `/usr/lib/libnetcdf.so.15`.

**Comment by mdsumner** [comment]
Can you `library(RNetCDF)`? 

I suspect it's about your RNetCDF installation - I'd try at the command line

```
nc-config
ncdump --help
```

Do they run ok? 

If they do, try re-installing RNetCDF.

**Comment by bbo2adwuff** [comment]
> I suspect it's about your RNetCDF installation...
True, I wasn't able to load it.

> If they do, try re-installing RNetCDF.
Yes, that worked, Thanks for the super quick reply :rocket:
