### ISSUE TITLE
0.1.0 release required

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/ncmeta#35]
`tidyr` will be submitted to CRAN on 2019-09-09, and so the recent updates here for the new tidyr syntax are needed to avoid warnings

https://github.com/hypertidy/ncmeta/commit/0518c2a38cdaae508f6255344b73673bae20b87e

I'm getting notifications for tidyr via tidync, it has the new behaviour for `nest()` but the changes in ncmeta aren't yet on CRAN. 

This means I really need to release an update before the end of August

@dblodgett-usgs how do you feel about that? I could craft a side branch if needed, but I gather a release of ncmeta would be reasonable in the next two weeks? (I will do checks of course, just wanted to give the heads up)

**Comment by dblodgett-usgs** [comment]
I'm available to test / work on things in the next couple weeks. So this is a good time to work on a release.

**Comment by mdsumner** [comment]
I'm going with 0.1.0

- [ ] local check passes, CRAN tidyr and dev tidyr
- [ ] pass on win Devel on CRAN
- [ ] docs updated
- [ ] rasterwise tour for sanity

**Comment by mdsumner** [comment]
So far so good, still waiting on winbuilder. I can submit this any time over the next week, so if you are happy let me know. I won't be able to do any stars checks, just FYI. @dblodgett-usgs

**Comment by mdsumner** [comment]
Awesome, thanks!  I just got winbuilder back so I'm going to submit. :)

**Comment by mdsumner** [comment]
Done!
